# site settings
title: 0=2
subtitle: Liber AL vel Legis
#email: youremailaddress@gmail.com
description: "We place no reliance on virgin or pigeon; our method is science, our aim is religion." # it will display as the sub-title
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://192.168.75.65:4000"  # the base hostname & protocol for your site
author: Aiwass
#$street_address: 1234 Somewhere Road
#c#ity: Nashville
#s#tate: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Kaleidox93
#  GitLab:
#  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
#  Instagram:
#  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#  Twitter: https://twitter.com/andrewbanchich
#  Facebook:
#  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md

jekyll_admin:
  hidden_links:
#    - posts
#    - pages
#    - staticfiles
#    - datafiles
#    - configuration
  homepage: "pages"

