jQuery(document).ready(function(){cryoutLpBoxesRatios();cryoutMobileMenuInit();cryoutFixedMobileMenu();cryoutInitNav('#mobile-menu');cryoutMenuAnimate();cryoutBackToTop();cryoutSearchFormAnimation();cryoutSocialTitles();cryoutBodyClasses();cryoutTabsWidget();cryoutPortfolioFilter();cryoutHeaderParallax();cryoutLPArrowLink();cryoutRemoveFocus();cryoutSliderTitleBreakUp('.lp-staticslider .staticslider-caption','.staticslider-caption-title > span');cryoutSliderTitleBreakUp('#header-page-title','#header-page-title .entry-title');cryoutAnimateLazyImages();if(typeof cryout_theme_settings!=='undefined'){if(((cryout_theme_settings.fitvids==2)&&(cryout_theme_settings.is_mobile==1))||(cryout_theme_settings.fitvids==1)){jQuery('.entry-content').fitVids();}
if(cryout_theme_settings.autoscroll==1){cryoutAutoScroll();}
if(cryout_theme_settings.articleanimation){animateScroll('#content-masonry > article','animated-onscroll');animateScroll('.lp-block, .lp-box, .lp-text, .lp-port, .lp-tt, '+'.lp-section-title, .lp-section-desc','animated-onscroll-lp');}}
jQuery(window).on('scroll',function(){if(jQuery(this).scrollTop()>30){jQuery('#nav-fixed').addClass('nav-fixed-show');}else{jQuery('#nav-fixed').removeClass('nav-fixed-show');}
if(jQuery(this).scrollTop()>100&&(!jQuery('.site-header-top').hasClass('is-active'))){jQuery('.bravada-fixed-menu .site-header-bottom').addClass('header-fixed');}else{jQuery('.bravada-fixed-menu .site-header-bottom').removeClass('header-fixed');}});});jQuery(window).on('load',function(){cryoutPreloader();jQuery(window).trigger('scroll');cryoutMasonry();cryoutPortfolioMasonry();});function cryoutAnimateLazyImages(){jQuery('body:not(.bravada-lazy-noanimation) #content img[loading="lazy"]').on('load',function(){jQuery(this).addClass('animate-lazy');}).each(function(){if(this.complete){jQuery(this).trigger('load');}});}
function cryoutPreloader(){if(!jQuery('.cryout-preloader').length)return;if(jQuery('.cryout-preloader').length)jQuery('.cryout-preloader').css('animation','none');jQuery('.cryout-preloader').fadeOut(700,function(){jQuery(this).remove();});}
function cryoutLPArrowLink(){if(!jQuery('body').hasClass('bravada-landing-page'))return;var newLink=jQuery('.main section.lp-slider + section').attr('id');if(undefined!==newLink&&newLink.length){jQuery('.meta-arrow').attr('href','#'+newLink);}}
function cryoutBurgerMenu(){if(!jQuery('.hamburger').length)return;var $activeElements=jQuery('.hamburger, #site-wrapper, .site-header-bottom-fixed, #mobile-menu');var fixedHeader=false;jQuery('.hamburger').on('click',function(e){$activeElements.toggleClass('is-active');jQuery('.site-header-top').prepareTransition().toggleClass('is-active');if(jQuery('.site-header-bottom').hasClass('header-fixed')){jQuery('.site-header-bottom').removeClass('header-fixed');fixedHeader=true;}
e.stopPropagation();});}
function cryoutLpBoxesRatios(){for(var index=1;index<=cryout_theme_settings.lpboxratios.length;++index){jQuery('.lp-boxes-'+index+' .lp-box-image').keepRatio(cryout_theme_settings.lpboxratios[index-1]);}}
function cryoutMenuAnimate(){jQuery('#access > .menu ul li > a:not(:only-child)').attr('aria-haspopup','true');jQuery('#access li').on('mouseenter',function(){jQuery(this).addClass('menu-hover');}).on('mouseleave',function(){jQuery(this).removeClass('menu-hover');});jQuery('#access ul').find('a').on('focus',function(){jQuery(this).parents('.menu-item, .page_item').addClass('menu-hover');});jQuery('#access ul').find('a').on('blur',function(){jQuery(this).parents('.menu-item, .page_item').removeClass('menu-hover');});}
function cryoutSliderTitleBreakUp(titleContainer,animatedTitle){titleContainer='body.bravada-animated-title '+titleContainer;animatedTitle='body.bravada-animated-title '+animatedTitle;if(!jQuery(animatedTitle).length)return;jQuery(titleContainer).addClass('animated-title');jQuery(window).on('scroll',function(){var el=jQuery(titleContainer);if(!isInViewport(el)){el.removeClass('animated-title');}else{el.addClass('animated-title');}});var $location=jQuery(animatedTitle),oldStr=$location.html(),clearStr=$location.text().split(' ').join(''),newStr='<em class="caption-title-word">',firsRunDelay=1000,letterDelay=0,animatedLetters=[],nrOfAnimatedLetters=(Math.floor(clearStr.length / 4)>2)?Math.floor(clearStr.length / 4):2;nrOfAnimatedLetters=(nrOfAnimatedLetters>7)?7:nrOfAnimatedLetters;var interval=3500+nrOfAnimatedLetters*letterDelay;for(var i=0;i<oldStr.length;i++){if(oldStr[i]=='<'){var substring=oldStr.substring(i);substring=substring.match(/(.*?)(<([^>]+)>)/ig);substring=substring[0];newStr+=substring;i+=substring.length-1;}else if(oldStr[i]=='&'){var substring=oldStr.substring(i);substring=substring.match(/(.*?);/ig);substring=substring[0];newStr+='<span><span class="cry-single">'+substring+'</span><span class="cry-double">'+substring+'</span></span>';i+=substring.length-1;}else if(oldStr[i]!=' '){newStr+='<span><span class="cry-single">'+oldStr[i]+'</span><span class="cry-double">'+oldStr[i]+'</span></span>';}else{newStr+='<span>&nbsp;</span></em><em class="caption-title-word">';}}
newStr+='</em>';$location.html(newStr);function titleAnimation(){jQuery(animatedTitle+' .cry-single, '+animatedTitle+' .cry-double').removeClass('animated-letter').css('animation-delay','0s');for(var i=0;i<nrOfAnimatedLetters;i++){animatedLetters[i]=Math.floor(Math.random()*clearStr.length);jQuery(animatedTitle+' .cry-single').eq(animatedLetters[i]).addClass('animated-letter').css('animation-delay',i*letterDelay+'ms');jQuery(animatedTitle+' .cry-double').eq(animatedLetters[i]).addClass('animated-letter').css('animation-delay',i*letterDelay+'ms');}}
setTimeout(titleAnimation,firsRunDelay);window.setInterval(titleAnimation,interval);}
function cryoutBackToTop(){jQuery(window).on('scroll',function(){if(jQuery(this).scrollTop()>500){jQuery('#toTop').addClass('toTop-show');}else{jQuery('#toTop').removeClass('toTop-show');}});jQuery('#toTop').on('click',function(event){event.preventDefault();jQuery('html, body').animate({scrollTop:0},500);return false;});}
function cryoutSearchFormAnimation(){var searchIcon=jQuery('#access .menu-search-animated > button'),searchForm=jQuery('.menu-search-animated .searchform, .menu-main-search .icon-cancel'),searchInput=jQuery('#access .menu-search-animated .s');searchIcon.on('click',function(event){event.preventDefault();searchForm.fadeIn(200,function(){searchInput.trigger('focus');searchInput.css('outline','none');});searchInput.addClass('is-active');event.stopPropagation();});searchForm.on('click',function(event){event.stopPropagation();});searchInput.on('blur',function(){searchInput.removeClass('is-active');searchForm.fadeOut(200);});}
function cryoutMobileMenuInit(){jQuery('#mobile-menu .menu-main-search').removeClass('menu-search-animated');var firstTab=jQuery('nav#mobile-menu #mobile-nav > li:first-child a'),lastTab=jQuery('.hamburger');jQuery('.hamburger').on('click',function(e){e.stopPropagation();jQuery('body').toggleClass('burgermenu-active noscroll');jQuery('nav#mobile-menu').prepareTransition().toggleClass('burgermenu-active');if(jQuery('body').hasClass('burgermenu-active')){firstTab.trigger('focus').trigger('blur');}else{lastTab.trigger('focus').trigger('blur');}});jQuery('nav#mobile-menu #mobile-nav > li, .side-section-element.widget_cryout_socials a').each(function(index){var value=0.03*index+'s';jQuery(this).css('-webkit-transition-delay',value);jQuery(this).css('transition-delay',value);});lastTab.on('keydown',function(e){if(jQuery('body').hasClass('burgermenu-active'))
if((e.which===9&&(!e.shiftKey))){e.preventDefault();firstTab.trigger('focus');}});firstTab.on('keydown',function(e){if(jQuery('body').hasClass('burgermenu-active'))
if((e.which===9&&e.shiftKey)){e.preventDefault();lastTab.trigger('focus');}});jQuery('nav#mobile-menu').on('keyup',function(e){if(jQuery('body').hasClass('burgermenu-active'))
if(e.keyCode===27){jQuery('body').removeClass('burgermenu-active noscroll');jQuery('nav#mobile-menu').prepareTransition().toggleClass('burgermenu-active');lastTab.trigger('focus');}});jQuery('nav#mobile-menu li a').on('click',function(e){var $hash=jQuery(this).prop('hash');if($hash&&jQuery($hash).length){jQuery('body').removeClass('burgermenu-active noscroll');jQuery('nav#mobile-menu').prepareTransition().toggleClass('burgermenu-active');}});}
function cryoutFixedMobileMenu(){if(cryout_theme_settings.menustyle!=1)return;var c,currentScrollTop=0,currentScrollBottom,navbar=jQuery('.site-header-bottom'),body=jQuery('body');jQuery(window).on('scroll',function(){var a=jQuery(window).scrollTop();var b=jQuery(document).height();var viewport=jQuery(window).height();var navbarHeight=navbar.height();currentScrollTop=a;currentScrollBottom=b;if(c<currentScrollTop&&a>navbarHeight+navbarHeight){body.removeClass('mobile-fixed');}else if((currentScrollTop>viewport)&&(currentScrollTop<currentScrollBottom-viewport*2)&&(c>currentScrollTop)&&(!(a<=navbarHeight))){body.addClass('mobile-fixed');}
c=currentScrollTop;if(currentScrollTop<=navbarHeight){body.removeClass('mobile-fixed');}});}
function cryoutInitNav(selector){var container=jQuery(selector);container.find('.menu-item-has-children > a').after('<button class="dropdown-toggle" aria-expanded="false"></button>');container.find('.page_item_has_children > a').after('<button class="dropdown-toggle" aria-expanded="false"></button>');container.find('.current-menu-ancestor > button, .current-page-ancestor > button').addClass('toggle-on');container.find('.current-menu-ancestor > .sub-menu, .current-page-ancestor > .sub-menu,'+' .current-menu-ancestor .children, .current-page-ancestor .children').show(0).addClass('toggled-on');container.find('.dropdown-toggle').on('click',function(e){var _this=jQuery(this);e.preventDefault();_this.toggleClass('toggle-on');if(_this.hasClass('toggle-on')){_this.next('.children, .sub-menu').show(0).addClass('toggled-on');_this.prev('a').addClass('toggled-on');}
else{_this.next('.children, .sub-menu').removeClass('toggled-on');_this.next('.children, .sub-menu').find('.children, .sub-menu').removeClass('toggled-on');_this.next('.children, .sub-menu').find('a').removeClass('toggled-on');_this.next('.children, .sub-menu').find('.dropdown-toggle').removeClass('toggled-on');_this.prev('a').removeClass('toggled-on');setTimeout(function(){_this.next('.children, .sub-menu').hide(0);_this.next('.children, .sub-menu').find('.children, .sub-menu').hide(0);},600);}
_this.attr('aria-expanded',_this.attr('aria-expanded')==='false'?'true':'false');});jQuery('body').on('click','#mobile-nav a',function(){jQuery('#nav-cancel i').trigger('click');});}
jQuery.fn.keepRatio=function(ratio){var $this=jQuery(this);var nh=$this.width()/ ratio;$this.css('height',nh+'px');jQuery(window).on('resize',function(){var nh=$this.width()/ ratio;$this.css('height',nh+'px');});};jQuery.fn.mousedir=function(el){if(!jQuery('body').hasClass('bravada-landing-page'))return;var $this=jQuery(this),$el=jQuery(el),last_position={},$output='direction-down';jQuery(document).on('mousemove',function(event){if(typeof(last_position.x)!=='undefined'){var deltaX=last_position.x-event.offsetX,deltaY=last_position.y-event.offsetY;if((Math.abs(deltaX)>Math.abs(deltaY))&&(deltaX>0)){$output='direction-left';}else if((Math.abs(deltaX)>Math.abs(deltaY))&&(deltaX<0)){$output='direction-right';}else if((Math.abs(deltaY)>Math.abs(deltaX))&&(deltaY>0)){$output='direction-up';}else if((Math.abs(deltaY)>Math.abs(deltaX))&&(deltaY<0)){$output='direction-down';}else{$output='direction-down';}}
last_position={x:event.offsetX,y:event.offsetY};});$el.on('mouseenter',function(){jQuery(this).removeClass('in-direction-left in-direction-right in-direction-up in-direction-down'+' out-direction-left out-direction-right out-direction-up out-direction-down');jQuery(this).addClass('in-'+$output);return;});$el.on('mouseleave',function(){jQuery(this).removeClass('in-direction-left in-direction-right in-direction-up in-direction-down '+' out-direction-left out-direction-right out-direction-up out-direction-down');jQuery(this).addClass('out-'+$output);return;});};function isInViewport(el){if(!jQuery(el).length)return;var adminHeight=(jQuery('#wpadminbar').length)?jQuery('#wpadminbar').height():0;var elementTop=jQuery(el).offset().top;var elementBottom=elementTop+jQuery(el).outerHeight();var viewportTop=jQuery(window).scrollTop();var viewportBottom=viewportTop+jQuery(window).height()-adminHeight;return(elementBottom>viewportTop)&&(elementTop<viewportBottom);}
function animateScroll($articles,$class){var $articles=jQuery($articles);$articles.each(function(i,el){jQuery(el).addClass($class);});jQuery(window).on('scroll',function(){$articles.each(function(i,el){if(isInViewport(el)){jQuery(el).removeClass($class);}});});jQuery(window).trigger('scroll');}
function cryoutHeaderParallax(){var cur_op=parseFloat(jQuery('#header-overlay').css('opacity'));jQuery(window).on('scroll',function(){var scrolled=jQuery(window).scrollTop();jQuery('#masthead .header-image').each(function(index,element){if(jQuery(element).css('display')==='none')return true;var initY=jQuery(element).offset().top,height=jQuery(element).height(),visible=isInViewport(jQuery(element));if(visible){var diff=scrolled-initY;var ratio=Math.round((diff / height)*100);jQuery(element).css('opacity',1);jQuery(element).css('background-position','center '+(50+parseInt(ratio))+'%');if((parseInt(ratio)>0)){jQuery('#header-overlay').css('opacity',cur_op+1.5*(parseInt(ratio)/(100 /((1-cur_op)*100))/ 100));jQuery('#header-page-title').css('opacity',(1-(parseInt(ratio)*1 / 100)));}else{jQuery('#header-overlay').css('opacity',cur_op);jQuery('#header-page-title').css('opacity',1);}}});});}
function cryoutSocialTitles(){jQuery('.socials a').each(function(){jQuery(this).attr('title',jQuery(this).children().html());jQuery(this).html('');});}
function cryoutBodyClasses(){if(((navigator.userAgent.indexOf('Safari')!==-1)||(navigator.userAgent.indexOf('iPhone')!==-1)||(navigator.userAgent.indexOf('iPad')!==-1))&&(navigator.userAgent.indexOf('Chrome')===-1)){jQuery('body').addClass('safari');}
if(jQuery('#content-masonry').length>0){jQuery('body').addClass('bravada-with-masonry');}}
function cryoutRemoveFocus(){jQuery('input, textarea, select, a').on('focus',function(){if(jQuery(this).data('mousedown')||jQuery(this).data('mouseup')){jQuery(this).css('outline','none');}});}
function cryoutTabsWidget(){var tabsNav=jQuery('.cryout-wtabs-nav'),tabsNavLis=tabsNav.children('li');tabsNav.each(function(){var localthis=jQuery(this);localthis.next().children('.cryout-wtab').stop(true,true).children('li').hide().parent().siblings(localthis.find('a').attr('href')).children('li').show();localthis.children('li').first().addClass('active').stop(true,true).show();});tabsNavLis.on('click',function(e){var localthis=jQuery(this),tabs_duration=200;localthis.siblings().removeClass('active').end().addClass('active');localthis.parent().next().children('.cryout-wtab').stop(true,true).children('li').hide().parent().siblings(localthis.find('a').attr('href')).children('li').each(function(index){jQuery(this).fadeIn(tabs_duration*(index+1));});e.preventDefault();}).children(window.location.hash?'a[href="'+window.location.hash+'"]':'a:first').trigger('click');}
function cryoutMasonry(){if((cryout_theme_settings.masonry==1)&&(cryout_theme_settings.magazine!=1)&&(typeof jQuery.fn.masonry!=='undefined')){jQuery('#content-masonry').masonry({itemSelector:'article',columnWidth:'article',percentPosition:true,isRTL:cryout_theme_settings.rtl,});}}
function cryoutPortfolioMasonry(){if((cryout_theme_settings.masonry==1)&&(typeof jQuery.fn.masonry!=='undefined')){jQuery('#lp-portfolio .jetpack-portfolio-shortcode').masonry({itemSelector:'.portfolio-entry',columnWidth:'.portfolio-entry:not(.hidey)',percentPosition:true,isRTL:cryout_theme_settings.rtl,});}}
function cryoutPortfolioFilter(){jQuery('body').on('click','#portfolio-filter > a',function(e){e.preventDefault();jQuery('#portfolio-filter > a').removeClass('active');jQuery(this).addClass('active');var filter=jQuery(this).attr('data-slug');jQuery('#portfolio-masonry .portfolio-entry').each(function(i,elm){if(filter=='all'){jQuery(elm).removeClass('hidey').fadeIn('fast');}else{if(!jQuery(elm).hasClass('type-'+filter)){jQuery(elm).addClass('hidey').fadeOut('fast');}else{jQuery(elm).removeClass('hidey').fadeIn('fast');}}}).promise().done(function(){cryoutPortfolioMasonry();});return false;});};(function($){$.fn.prepareTransition=function(){return this.each(function(){var el=$(this);el.one('TransitionEnd webkitTransitionEnd transitionend oTransitionEnd',function(){el.removeClass('is-transitioning');});var cl=["transition-duration","-moz-transition-duration","-webkit-transition-duration","-o-transition-duration"];var duration=0;$.each(cl,function(idx,itm){duration||(duration=parseFloat(el.css(itm)));});if(duration!=0){el.addClass('is-transitioning');el[0].offsetWidth;}});};}(jQuery));function cryoutAutoScroll(document,history,location){document=window.document;history=window.history;location=window.location;var HISTORY_SUPPORT=!!(history&&history.pushState);var anchorScrolls={ANCHOR_REGEX:/^#[^ ]+$/,OFFSET_HEIGHT_PX:jQuery('.bravada-fixed-menu #site-header-main').height(),init:function(){this.scrollToCurrent();jQuery(window).on('hashchange',jQuery.proxy(this,'scrollToCurrent'));jQuery('body').on('click','.main a, nav ul li a, .meta-arrow',jQuery.proxy(this,'delegateAnchors'));},getFixedOffset:function(){return(this.OFFSET_HEIGHT_PX)?this.OFFSET_HEIGHT_PX:0;},scrollIfAnchor:function(href,pushToHistory){var match,anchorOffset;if(!this.ANCHOR_REGEX.test(href)){return false;}
match=document.getElementById(href.slice(1));if(match&&(!isInViewport(match))&&jQuery(match).offset().top){anchorOffset=jQuery(match).offset().top-this.getFixedOffset();jQuery('html, body').animate({scrollTop:anchorOffset});if(HISTORY_SUPPORT&&pushToHistory){history.pushState({},document.title,location.pathname+href);}}
return!!match;},scrollToCurrent:function(e){if(this.scrollIfAnchor(window.location.hash)&&e){e.preventDefault();}},delegateAnchors:function(e){var elem=e.target.closest('a');if(this.scrollIfAnchor(elem.getAttribute('href'),true)){e.preventDefault();}}};jQuery(document).ready(jQuery.proxy(anchorScrolls,'init'));};(function($){'use strict';$.fn.fitVids=function(options){var settings={customSelector:null,ignore:null};if(!document.getElementById('fit-vids-style')){var head=document.head||document.getElementsByTagName('head')[0];var css='.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}';var div=document.createElement("div");div.innerHTML='<p>x</p><style id="fit-vids-style">'+css+'</style>';head.appendChild(div.childNodes[1]);}
if(options){$.extend(settings,options);}
return this.each(function(){var selectors=['iframe[src*="player.vimeo.com"]','iframe[src*="youtube.com"]','iframe[src*="youtube-nocookie.com"]','iframe[src*="kickstarter.com"][src*="video.html"]','object','embed'];if(settings.customSelector){selectors.push(settings.customSelector);}
var ignoreList='.fitvidsignore, .wp-block-embed__wrapper';if(settings.ignore){ignoreList=ignoreList+', '+settings.ignore;}
var $allVideos=$(this).find(selectors.join(','));$allVideos=$allVideos.not('object object');$allVideos=$allVideos.not(ignoreList);$allVideos.each(function(){var $this=$(this);if($this.parents(ignoreList).length>0){return;}
if(this.tagName.toLowerCase()==='embed'&&$this.parent('object').length||$this.parent('.fluid-width-video-wrapper').length){return;}
if((!$this.css('height')&&!$this.css('width'))&&(isNaN($this.attr('height'))||isNaN($this.attr('width')))){$this.attr('height',9);$this.attr('width',16);}
var height=(this.tagName.toLowerCase()==='object'||($this.attr('height')&&!isNaN(parseInt($this.attr('height'),10))))?parseInt($this.attr('height'),10):$this.height(),width=!isNaN(parseInt($this.attr('width'),10))?parseInt($this.attr('width'),10):$this.width(),aspectRatio=height / width;if(!$this.attr('name')){var videoName='fitvid'+$.fn.fitVids._count;$this.attr('name',videoName);$.fn.fitVids._count++;}
$this.wrap('<div class="fluid-width-video-wrapper"></div>').parent('.fluid-width-video-wrapper').css('padding-top',(aspectRatio*100)+'%');$this.removeAttr('height').removeAttr('width');});});};$.fn.fitVids._count=0;})(window.jQuery||window.Zepto);if(window.Element&&(!Element.prototype.closest)){Element.prototype.closest=function(s){var matches=(this.document||this.ownerDocument).querySelectorAll(s),i,el=this;do{i=matches.length;while(--i>=0&&matches.item(i)!==el){}}while((i<0)&&(el=el.parentElement));return el;};}